### ISSUE TITLE
Variable expansion doesn't work

### ISSUE THREAD

**Issue by philhofer** [SnellerInc/grafana-datasource#13]
One of our prod query panels uses
```
${Services:singlequote}
```
to expand a list of select-able services as a list of single-quoted strings.

It seems like the backend datasource needs to understand how to handle these on its own.
https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#advanced-variable-format-options

**Comment by philhofer** [comment]
@flobernd is this something that can be done from the frontend before the query is sent to the backend? It seems like the front end ought to have the information available to do this. I'm not sure the backend does.

**Comment by philhofer** [comment]
Relevant: https://community.grafana.com/t/how-to-use-template-variables-in-your-data-source/63250

**Comment by flobernd** [comment]
@philhofer I will have a look! I remember there was a frontend service that can be used for variable expansion. Not sure if it handles this specific case by default, but I'll test it.

**Comment by philhofer** [comment]
The linked article says this is what you have to do for backend datasources:
```
export class DataSource extends DataSourceWithBackend<MyQuery, MyDataSourceOptions> {
  constructor(instanceSettings: DataSourceInstanceSettings<MyDataSourceOptions>) {
    super(instanceSettings);
  }

  applyTemplateVariables(query: MyQuery, scopedVars: ScopedVars): Record<string, any> {
    const interpolatedQuery: MyQuery = {
      ...query,
      rawQuery: getTemplateSrv().replace(rawQuery, scopedVars),
    };

    return interpolatedQuery;
  }
}
```

**Comment by flobernd** [comment]
@philhofer Yes, that looks like the code I used in the initial frontend version of the plugin. Probably forgot to add it again while converting to a backend plugin. I'll create a PR soon.
