### ISSUE TITLE
Order result-set columns by query projection ordering

### ISSUE THREAD

**Issue by philhofer** [SnellerInc/grafana-datasource#14]
The "Logs" visualization in Grafana always picks the first non-timestamp column as the log line.
Right now the textual order of the `SELECT` columns has no effect on the order of the result columns,
which means there isn't really a way to work around this shortcoming in the visualization.
It would be nice if the result order always matched the order presented in the textual query (to the extent that it's possible).

**Comment by flobernd** [comment]
This seems to be a general Sneller limitation. E.g.

```
SELECT duration, bytes FROM queries LIMIT 1

[
  {
    duration: 155238520,
    bytes: 53477376
  },
  final_status::{
    hits: 0,
    misses: 0,
    scanned: 0,
    result_set: {
      duration: 65535,
      bytes: 65535
    }
  }
]
```

```
SELECT bytes, duration FROM queries LIMIT 1

[
  {
    duration: 155238520,
    bytes: 53477376
  },
  final_status::{
    hits: 0,
    misses: 1,
    scanned: 1048576,
    result_set: {
      bytes: 65535,
      duration: 65535
    }
  }
]
```

In the `result_set` annotation field, the order of the `SELECT` columns is honored, in the actual result rows, it's not.

**Comment by philhofer** [comment]
Right; there isn't a way for us to fix this in the query engine because of the semantics of ion and the fact that we guarantee symbol IDs are sorted within structures. What I'm suggesting is just that the grafana datasource sort the columns in the data frame according to the returned `result_set`.

**Comment by flobernd** [comment]
Sounds good. I'll take care!
